services:
  php:
    image: webdevops/php-apache-dev:8.2
    working_dir: /application
    volumes:
      - ./:/application
    environment:
      WEB_DOCUMENT_ROOT: /application
      XDEBUG_MODE: debug
      XDEBUG_REMOTE_HOST: localhost
      XDEBUG_REMOTE_CONNECT_BACK: On
      XDEBUG_IDE_KEY: PHPSTORM
    ports:
      - 8000:80
      - 80:80

  bun:
    user: '${USER_ID}:${GROUP_ID}'
    image: oven/bun
    command: bun dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

